{
  "namespace": "backport",
  "short_name": "dataset_3075_year_of_last_rinderpest_case__oie__2018_values",
  "name": "Year of last Rinderpest case - OIE (2018)",
  "description": "",
  "source_name": "Our World in Data catalog backport",
  "url": "https://owid.cloud/admin/datasets/3075",
  "file_extension": "feather",
  "date_accessed": "2022-05-27T08:01:00.438082",
  "is_public": true,
  "version": "latest",
  "publication_date": "latest",
  "owid_data_url": "https://walden.nyc3.digitaloceanspaces.com/backport/latest/dataset_3075_year_of_last_rinderpest_case__oie__2018_values.feather",
  "md5": "aeddf10bb6e12c9da5c96e98e82e30f0"
}
